weather/urls.py
from django.urls import path

from . import views

app_name = "weather"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
]

weather_forecast_api/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("weather.urls")),
    path('admin/', admin.site.urls),

]

weather/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Forecast(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    date = models.DateField()
    max_temperature = models.DecimalField(max_digits=5, decimal_places=2)
    min_temperature = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.city}: {self.date} - Max: {self.max_temperature}, Min: {self.min_temperature}"

weather/views.py
from django.shortcuts import render
from weather.domain.services.city import CityService
from weather.domain.services.weather_day_forecast import WeatherDayForecast
from weather.domain.services.weather_forecast import WeatherForecastService
from weather_forecast_api.settings import (
    RESERVAMOS_BASE_URL,
    OPEN_WEATHER_BASE_URL,
    OPEN_WEATHER_API_KEY,
)


def index(request):
    return render(request, 'weather/index.html')


def search(request):
    print('request: ', request.GET)
    if not request.GET.get('city'):
        return render(
            request,
            "weather/index.html",
            {
                "error_message": "You didn't entry a city.",
            },
        )
    else:
        weather_day_forecast = WeatherDayForecast(
            city_to_search=request.GET['city'],
            city_service=CityService(
                base_url=RESERVAMOS_BASE_URL,
            ),
            weather_forecast_service=WeatherForecastService(
                base_url=OPEN_WEATHER_BASE_URL,
                api_key=OPEN_WEATHER_API_KEY,
            ),
        )
        cities_weather = weather_day_forecast.execute()
        return render(request, "weather/results.html", {
            'search': request.GET['city'],
            'cities': cities_weather,

        })

weather/templates/weather/index.html
<form action="{% url 'weather:search' %}" method="GET">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Search City</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="search">Enter a partial or total name of any city in Mexico</label><br>
            <input type="text" name="city" id="search">
            <button type="submit">Search</button>
    </fieldset>
</form>

weather/templates/weather/results.html
{% if search %}
    <h1>Search results for: {{ search }}</h1><br>
    <a href="{% url 'weather:index' %}">Search another city?</a>
    <ul>
    {% for item in cities %}
        <li>
            <h2>{{ item.city.name }}</h2>
            <ul>
            <li>(lat: {{ item.city.lat }},  lng: {{ item.city.lng }})</li>
                {% for day in item.weather_forecast %}
                     <li>
                     <h3>Weather on {{ day.day }}</h3>
                         <ul>
                             <li>Expected max temperature: {{ day.max }}</li>
                             <li>Expected min temperature: {{ day.min }}</li>
                             <li>Expected weather: {{ day.weather }}</li>
                         </ul>
                     </li>

                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
    <a href="{% url 'weather:index' %}">Search another city?</a>
{% else %}
    <p>There is not a city with that name</p>
    <a href="{% url 'weather:index' %}">Search another city?</a>
{% endif %}